codecov:
  token: fe38f18b-4146-45fe-bf84-f1d0a677a1df
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no
    patch: yes
    changes: no
comment:
  layout: "header, diff, changes, tree"
  behavior: default
