codecov:
  token: fe38f18b-4146-45fe-bf84-f1d0a677a1df
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: yes
    patch: yes
    changes: no
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
comment:
  layout: "header, diff"
  behavior: default
  require_changes: no